#spring.application.name=todoapp

spring:
  datasource:

    url: jdbc:mysql://lion-db.cpoeo06ycky0.ap-northeast-2.rds.amazonaws.com/mydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect